# Generated by Django 2.2.26 on 2022-03-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venyou_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name_slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
