# Generated by Django 2.2.26 on 2022-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venyou_app', '0003_auto_20220316_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='Glasgow', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='postcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
